# Generated by Django 6.0.3 on 2026-05-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_points_awarded_pointtransaction_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='depends_on',
            field=models.ManyToManyField(blank=True, related_name='blocked_tasks', to='tasks.comment'),
        ),
    ]
