# Generated by Django 6.0.3 on 2026-05-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_comment_depends_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='depends_on',
        ),
        migrations.AddField(
            model_name='task',
            name='depends_on',
            field=models.ManyToManyField(blank=True, related_name='blocked_tasks', to='tasks.task'),
        ),
    ]
