# Generated by Django 6.0.3 on 2026-05-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_remove_comment_depends_on_task_depends_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='graph_node_positions',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
